package entry.dsm.gitauth.equusgithubauth.domain.auth.exception

import entry.dsm.gitauth.equusgithubauth.global.exception.CustomException
import entry.dsm.gitauth.equusgithubauth.global.exception.ErrorCode

object AuthorizedClientNotFoundException : CustomException(ErrorCode.AUTHORIZED_CLIENT_NOT_FOUND)
